2021-01-21 08:26:21.657 [error] <0.775.0> CRASH REPORT Process <0.775.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"dce03b2d-1ae6-4f2d-82c0-f5dd598a77d4">>,<<"inserted_at">> => <<"2021-01-21T08:26:21">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:26:21">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/edfeb1ed-ada4-439c-892d-de8600038dda-gestao-de-obras-dicas.jpg">>}},...},...},...},...}
2021-01-21 08:26:21.668 [error] <0.775.0> Cowboy stream 2 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.768.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"dce03b2d-1ae6-4f2d-82c0-f5dd598a77d4">>,<<"inserted_at">> => <<"2021-01-21T08:26:21">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:26:21">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/edfeb1ed-ada4-439c-892d-de8600038dda-gestao-de-obras-dicas.jpg">>}},[...]},...},...}
2021-01-21 08:27:24.393 [error] <0.800.0> CRASH REPORT Process <0.800.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_channel,message => nil,module => 'Elixir.AMQP.Application',reason => nil},[{'Elixir.AMQP.Application',get_channel,[mychan],[]},{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,17}]},{'Elixir.ApiGalleryUpload.Upload',upload,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,10}]},{'Elixir.ApiGalleryUploadWeb.UploadController',create,2,[{file,...},...]},...]},...},...},...}
2021-01-21 08:27:24.394 [error] <0.800.0> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.799.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_channel,message => nil,module => 'Elixir.AMQP.Application',reason => nil},[{'Elixir.AMQP.Application',get_channel,[mychan],[]},{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,17}]},{'Elixir.ApiGalleryUpload.Upload',upload,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,10}]},{'Elixir.ApiGalleryUploadWeb.UploadController',create,2,[{file,...},...]},...]},...},...}
2021-01-21 08:29:58.396 [error] <0.628.0> Supervisor 'Elixir.ApiGalleryUploadWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.ApiGalleryUploadWeb.Endpoint.HTTP']}]) at <0.751.0> exit with reason killed in context shutdown_error
2021-01-21 08:30:34.680 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_channel,message => nil,module => 'Elixir.AMQP.Application',reason => nil},[{'Elixir.AMQP.Application',get_channel,[mychan],[]},{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,17}]},{'Elixir.ApiGalleryUpload.Upload',upload,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,10}]},{'Elixir.ApiGalleryUploadWeb.UploadController',create,2,[{file,...},...]},...]},...},...},...}
2021-01-21 08:30:34.697 [error] <0.754.0> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.753.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_channel,message => nil,module => 'Elixir.AMQP.Application',reason => nil},[{'Elixir.AMQP.Application',get_channel,[mychan],[]},{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,17}]},{'Elixir.ApiGalleryUpload.Upload',upload,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,10}]},{'Elixir.ApiGalleryUploadWeb.UploadController',create,2,[{file,...},...]},...]},...},...}
2021-01-21 08:34:22.494 [error] emulator Error in process <0.464.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"fec894c6-9a84-47b3-b9cf-4d4b12c2b3be">>,<<"inserted_at">> => <<"2021-01-21T08:34:22">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:34:22">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/13504522-a7c0-443b-8d89-554c00e45001-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/13504522-a7c0-443b-8d89-554c00e45001-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:34:22.495 [error] <0.453.0>@lists:reverse:147 Supervisor {<0.453.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.463.0>, {<<"client 172.27.0.6:32791 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.464.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"fec89...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:34:22.496 [error] <0.453.0> Supervisor {<0.453.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.463.0>, {<<"client 172.27.0.6:32791 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.464.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:34:22.561 [error] <0.390.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.633.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:34:22.588 [error] <0.390.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.633.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:34:22.591 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.390.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.633.0>,open,70000]}} in context child_terminated
2021-01-21 08:35:04.817 [error] emulator Error in process <0.648.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"62133649-3148-4247-bff3-543a18f44c49">>,<<"inserted_at">> => <<"2021-01-21T08:35:04">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:35:04">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/1dc35a42-9db7-4bf1-99dc-6b4bbdad0c97-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/1dc35a42-9db7-4bf1-99dc-6b4bbdad0c97-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:35:04.819 [error] <0.645.0>@lists:reverse:147 Supervisor {<0.645.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.647.0>, {<<"client 172.27.0.6:37891 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.648.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"62133...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:35:04.820 [error] <0.645.0> Supervisor {<0.645.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.647.0>, {<<"client 172.27.0.6:37891 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.648.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:35:04.831 [error] <0.642.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.660.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:35:04.837 [error] <0.642.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.660.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:35:04.838 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.642.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.660.0>,open,70000]}} in context child_terminated
2021-01-21 08:35:06.860 [error] <0.675.0>@lists:reverse:147 CRASH REPORT Process <0.675.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"231bd...">>,...},...}) line 147
2021-01-21 08:35:06.862 [error] <0.672.0>@lists:reverse:147 Supervisor {<0.672.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.674.0>, {<<"client 172.27.0.6:41025 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.675.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"231bd...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:35:06.862 [error] <0.672.0> Supervisor {<0.672.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.674.0>, {<<"client 172.27.0.6:41025 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.675.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:35:06.871 [error] <0.662.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.683.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:35:06.877 [error] <0.662.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.683.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:35:06.879 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.662.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.683.0>,open,70000]}} in context child_terminated
2021-01-21 08:35:08.988 [error] <0.698.0>@lists:reverse:147 CRASH REPORT Process <0.698.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"97831...">>,...},...}) line 147
2021-01-21 08:35:08.990 [error] <0.695.0>@lists:reverse:147 Supervisor {<0.695.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.14>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.697.0>, {<<"client 172.27.0.6:37073 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.698.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"97831...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:35:08.991 [error] <0.695.0> Supervisor {<0.695.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.14>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.697.0>, {<<"client 172.27.0.6:37073 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.698.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:35:08.998 [error] <0.688.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.706.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:35:09.003 [error] <0.688.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.706.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:35:09.004 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.688.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.706.0>,open,70000]}} in context child_terminated
2021-01-21 08:36:22.697 [error] <0.718.0>@lists:reverse:147 Supervisor {<0.718.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.720.0>, {<<"client 172.27.0.6:34681 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.721.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"f4d03...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:36:22.697 [error] <0.718.0> Supervisor {<0.718.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.720.0>, {<<"client 172.27.0.6:34681 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.721.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:36:22.699 [error] emulator Error in process <0.721.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"f4d031f7-a090-4027-98e3-f6e8fa215e5a">>,<<"inserted_at">> => <<"2021-01-21T08:36:22">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:36:22">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/1c4078e7-3b95-4f4a-8e60-8e3584bdcb5e-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/1c4078e7-3b95-4f4a-8e60-8e3584bdcb5e-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:36:22.713 [error] <0.708.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.750.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:36:22.714 [error] <0.708.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.750.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:36:22.715 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.708.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.750.0>,open,70000]}} in context child_terminated
2021-01-21 08:36:25.926 [error] <0.765.0>@lists:reverse:147 CRASH REPORT Process <0.765.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"b17c2...">>,...},...}) line 147
2021-01-21 08:36:25.928 [error] <0.762.0>@lists:reverse:147 Supervisor {<0.762.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.19>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.764.0>, {<<"client 172.27.0.6:36945 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.765.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"b17c2...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:36:25.928 [error] <0.762.0> Supervisor {<0.762.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.19>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.764.0>, {<<"client 172.27.0.6:36945 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.765.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:36:25.941 [error] <0.752.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.773.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:36:25.945 [error] <0.752.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.773.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:36:25.946 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.752.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.773.0>,open,70000]}} in context child_terminated
2021-01-21 08:37:41.607 [error] <0.785.0>@lists:reverse:147 Supervisor {<0.785.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.787.0>, {<<"client 172.27.0.6:60485 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.788.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"b590b...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:37:41.608 [error] emulator Error in process <0.788.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"b590b4a0-de88-42ef-8ba3-c83f6ce4db18">>,<<"inserted_at">> => <<"2021-01-21T08:37:41">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:37:41">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/428a0320-d87b-4376-9f8e-2e1cf975b4aa-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/428a0320-d87b-4376-9f8e-2e1cf975b4aa-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:37:41.609 [error] <0.785.0> Supervisor {<0.785.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.787.0>, {<<"client 172.27.0.6:60485 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.788.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:37:41.629 [error] <0.777.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.816.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:37:41.637 [error] <0.777.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.816.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:37:41.638 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.777.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.816.0>,open,70000]}} in context child_terminated
2021-01-21 08:37:41.767 [error] <0.792.0> CRASH REPORT Process <0.792.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => inspect,kind => nil,module => 'Elixir.IO'},[{'Elixir.IO',inspect,[stdio,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.778.0>},custom_consumer => {'Elixir.AMQP.SelectiveConsumer',<0.777.0>},pid => <0.787.0>},ok],[{file,"lib/io.ex"},{line,414}]},{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_galler..."},...]},...]},...},...},...}
2021-01-21 08:37:41.769 [error] <0.792.0> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.791.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => inspect,kind => nil,module => 'Elixir.IO'},[{'Elixir.IO',inspect,[stdio,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.778.0>},custom_consumer => {'Elixir.AMQP.SelectiveConsumer',<0.777.0>},pid => <0.787.0>},ok],[{file,"lib/io.ex"},{line,414}]},{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_..."},...]},...]},...},...}
2021-01-21 08:38:07.057 [error] emulator Error in process <0.831.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"6175087c-559a-4a95-9c3d-d5f0afe1be03">>,<<"inserted_at">> => <<"2021-01-21T08:38:07">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:38:07">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/48fa4339-d334-481a-bf68-15654e9a61e1-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/48fa4339-d334-481a-bf68-15654e9a61e1-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:38:07.067 [error] <0.828.0>@lists:reverse:147 Supervisor {<0.828.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.24>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.830.0>, {<<"client 172.27.0.6:34939 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.831.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"61750...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:38:07.068 [error] <0.828.0> Supervisor {<0.828.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.24>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.830.0>, {<<"client 172.27.0.6:34939 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.831.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:38:07.076 [error] <0.821.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.855.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:38:07.084 [error] <0.821.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.855.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:38:07.085 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.821.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.855.0>,open,70000]}} in context child_terminated
2021-01-21 08:39:35.494 [error] emulator Error in process <0.870.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"adba702f-2e41-40a4-8a1e-0829750e7816">>,<<"inserted_at">> => <<"2021-01-21T08:39:35">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:39:35">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/7af1c0d7-8c03-42e5-83a4-630f7b3fe039-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/7af1c0d7-8c03-42e5-83a4-630f7b3fe039-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:39:35.495 [error] <0.867.0>@lists:reverse:147 Supervisor {<0.867.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.26>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.869.0>, {<<"client 172.27.0.6:51277 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.870.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"adba7...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:39:35.496 [error] <0.867.0> Supervisor {<0.867.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.26>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.869.0>, {<<"client 172.27.0.6:51277 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.870.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:39:35.506 [error] <0.857.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.886.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:39:35.515 [error] <0.857.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.886.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:39:35.523 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.857.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.886.0>,open,70000]}} in context child_terminated
2021-01-21 08:42:07.056 [error] emulator Error in process <0.901.0> with exit value:
{function_clause,[{lists,reverse,[#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"87ccbb1f-0e0b-4072-9bc3-10f688a4d809">>,<<"inserted_at">> => <<"2021-01-21T08:42:07">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T08:42:07">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/645a083f-daa7-4379-8f52-e68c2cacef33-gestao-de-obras-dicas.jpg">>},url => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/645a083f-daa7-4379-8f52-e68c2cacef33-gestao-de-obras-dicas.jpg">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/app/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/app/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-01-21 08:42:07.058 [error] <0.898.0>@lists:reverse:147 Supervisor {<0.898.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.30>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.900.0>, {<<"client 172.27.0.6:52905 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.901.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"87ccb...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:42:07.058 [error] <0.898.0> Supervisor {<0.898.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.30>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.900.0>, {<<"client 172.27.0.6:52905 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.901.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:42:07.069 [error] <0.895.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.916.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:42:07.075 [error] <0.895.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.916.0>,open,70000]}} in gen_server:call/3 line 223
2021-01-21 08:42:07.076 [error] <0.388.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.895.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.916.0>,open,70000]}} in context child_terminated
2021-01-21 08:43:38.590 [error] <0.935.0> CRASH REPORT Process <0.935.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,econnrefused}},[{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,17}]},{'Elixir.ApiGalleryUpload.Upload',upload,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,10}]},{'Elixir.ApiGalleryUploadWeb.UploadController',create,2,[{file,"lib/api_gallery_upload_web/controllers/upload_controller.ex"},{line,9}]},{'Elixir.ApiGalleryUploadWeb.UploadController',action,2,[{file,...},...]},...]},...},...},...}
2021-01-21 08:43:38.592 [error] <0.935.0> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.934.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,econnrefused}},[{'Elixir.ApiGalleryUpload.Upload',sendQueue,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,17}]},{'Elixir.ApiGalleryUpload.Upload',upload,1,[{file,"lib/api_gallery_upload/upload.ex"},{line,10}]},{'Elixir.ApiGalleryUploadWeb.UploadController',create,2,[{file,"lib/api_gallery_upload_web/controllers/upload_controller.ex"},{line,9}]},{'Elixir.ApiGalleryUploadWeb.UploadController',action,2,[{file,...},...]},...]},...},...}
2021-01-21 08:49:36.278 [error] <0.745.0>@lists:reverse:147 CRASH REPORT Process <0.745.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"876e4...">>,...},...}) line 147
2021-01-21 08:49:36.279 [error] <0.742.0>@lists:reverse:147 Supervisor {<0.742.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.43>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.744.0>, {<<"client 172.27.0.6:53459 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.745.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"876e4...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:49:36.280 [error] <0.742.0> Supervisor {<0.742.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.43>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.744.0>, {<<"client 172.27.0.6:53459 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.745.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:51:57.559 [error] <0.853.0>@lists:reverse:147 CRASH REPORT Process <0.853.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"5ef9e...">>,...},...}) line 147
2021-01-21 08:51:57.563 [error] <0.850.0>@lists:reverse:147 Supervisor {<0.850.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.75>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.852.0>, {<<"client 172.27.0.6:55049 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.853.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"5ef9e...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:51:57.564 [error] <0.850.0> Supervisor {<0.850.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.75>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.852.0>, {<<"client 172.27.0.6:55049 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.853.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:52:36.622 [error] <0.501.0> Supervisor 'Elixir.ApiGalleryUploadWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.ApiGalleryUploadWeb.Endpoint.HTTP']}]) at <0.624.0> exit with reason killed in context shutdown_error
2021-01-21 08:52:39.166 [error] <0.405.0> gen_server 'Elixir.AMQP.Application.Channel::mychan' terminated with reason: {timeout,{'Elixir.GenServer',call,['Elixir.AMQP.Application.Connection::myconn',get_connection,5000]}} in 'Elixir.GenServer':call/3 line 1023
2021-01-21 08:52:39.210 [error] <0.405.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::mychan' with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,['Elixir.AMQP.Application.Connection::myconn',get_connection,5000]}} in 'Elixir.GenServer':call/3 line 1023
2021-01-21 08:52:39.210 [error] <0.403.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::mychan' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,myconn},{proc_name,mychan}]) at <0.405.0> exit with reason {timeout,{'Elixir.GenServer',call,['Elixir.AMQP.Application.Connection::myconn',get_connection,5000]}} in context shutdown_error
2021-01-21 08:53:09.144 [error] <0.643.0>@lists:reverse:147 CRASH REPORT Process <0.643.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"08abe...">>,...},...}) line 147
2021-01-21 08:53:09.145 [error] <0.640.0>@lists:reverse:147 Supervisor {<0.640.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.642.0>, {<<"client 172.27.0.6:54481 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.643.0> exit with reason no function clause matching lists:reverse(#{image => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"08abe...">>,...},...}) line 147 in context child_terminated
2021-01-21 08:53:09.146 [error] <0.640.0> Supervisor {<0.640.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.642.0>, {<<"client 172.27.0.6:54481 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.643.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 08:59:13.650 [error] <0.558.0>@lists:reverse:147 CRASH REPORT Process <0.558.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse({}) line 147
2021-01-21 08:59:13.651 [error] <0.555.0>@lists:reverse:147 Supervisor {<0.555.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.557.0>, {<<"client 172.27.0.6:48373 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.558.0> exit with reason no function clause matching lists:reverse({}) line 147 in context child_terminated
2021-01-21 08:59:13.652 [error] <0.555.0> Supervisor {<0.555.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.557.0>, {<<"client 172.27.0.6:48373 -> 172.27.0.3:5672">>,1}, false, 1000000000) at <0.558.0> exit with reason reached_max_restart_intensity in context shutdown
2021-01-21 09:06:46.373 [error] <0.640.0> CRASH REPORT Process <0.640.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"d4a392e0-7af1-4d85-96ec-4466a94a6b11">>,<<"inserted_at">> => <<"2021-01-21T09:06:46">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T09:06:46">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/fa10248d-eb1b-4602-8f85-2d7766fa1cc2-gestao-de-obras-dicas.jpg">>}},...},...},...},...}
2021-01-21 09:06:46.381 [error] <0.640.0> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.639.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{<<"gallery_id">> => <<"1cf7264d-f4f9-4aed-877a-687e69392e76">>,<<"id">> => <<"d4a392e0-7af1-4d85-96ec-4466a94a6b11">>,<<"inserted_at">> => <<"2021-01-21T09:06:46">>,<<"title">> => <<"gestao-de-obras-dicas.jpg">>,<<"updated_at">> => <<"2021-01-21T09:06:46">>,<<"url">> => <<"https://criativoweb-bucket.s3.amazonaws.com/teste-v2/fa10248d-eb1b-4602-8f85-2d7766fa1cc2-gestao-de-obras-dicas.jpg">>}},[...]},...},...}
2021-01-21 09:12:04.333 [error] <0.514.0> Supervisor 'Elixir.ApiGalleryUploadWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.ApiGalleryUploadWeb.Endpoint.HTTP']}]) at <0.637.0> exit with reason killed in context shutdown_error
2021-01-22 09:16:51.988 [error] <0.524.0>@Elixir.ApiGalleryUploadWeb.UserSocket:child_spec Supervisor 'Elixir.ApiGalleryUpload.Supervisor' had child 'Elixir.ApiGalleryUploadWeb.Endpoint' started with 'Elixir.ApiGalleryUploadWeb.Endpoint':start_link([]) at undefined exit with reason call to undefined function 'Elixir.ApiGalleryUploadWeb.UserSocket':child_spec([{endpoint,'Elixir.ApiGalleryUploadWeb.Endpoint'},{websocket,true},{longpoll,false}]) in context start_error
2021-01-22 09:16:51.988 [error] <0.533.0>@Elixir.ApiGalleryUploadWeb.UserSocket:child_spec CRASH REPORT Process <0.533.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.ApiGalleryUploadWeb.UserSocket':child_spec([{endpoint,'Elixir.ApiGalleryUploadWeb.Endpoint'},{websocket,true},{longpoll,false}])
2021-01-22 09:16:51.989 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ApiGalleryUploadWeb.Endpoint',{undef,[{'Elixir.ApiGalleryUploadWeb.UserSocket',child_spec,[[{endpoint,'Elixir.ApiGalleryUploadWeb.Endpoint'},{websocket,true},{longpoll,false}]],[]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.Phoenix.Endpoint.Supervisor',init,1,[{file,"lib/phoenix/endpoint/supervisor.ex"},{line,105}]},{supervisor,init,...},...]}}},...} in application_master:init/4 line 138
2021-01-22 09:17:22.287 [error] <0.871.0> CRASH REPORT Process <0.871.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => upload,kind => nil,module => 'Elixir.ApiGalleryUpload.Upload'},[{'Elixir.ApiGalleryUpload.Upload',upload,[#{<<"image">> => #{'__struct__' => 'Elixir.Plug.Upload',content_type => <<"image/jpeg">>,filename => <<"gestao-de-obras-dicas.jpg">>,path => <<"/tmp/plug-1611/multipart-1611307042-25621176655598-4">>}}],[{file,"lib/api_gallery_upload/upload.ex"},{line,6}]},{'Elixir.ApiGalleryUploadWeb.UploadController',...},...]},...},...},...}
2021-01-22 09:17:22.306 [error] <0.871.0> Cowboy stream 3 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.800.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => upload,kind => nil,module => 'Elixir.ApiGalleryUpload.Upload'},[{'Elixir.ApiGalleryUpload.Upload',upload,[#{<<"image">> => #{'__struct__' => 'Elixir.Plug.Upload',content_type => <<"image/jpeg">>,filename => <<"gestao-de-obras-dicas.jpg">>,path => <<"/tmp/plug-1611/multipart-1611307042-25621176655598-4">>}}],[{file,"lib/api_gallery_upload/upload.ex"},{line,6}]},{'Elixir.ApiGalleryUploadWeb.UploadController',...},...]},...},...}
2021-01-23 17:50:58.238 [error] <0.633.0> Supervisor 'Elixir.ApiGalleryUploadWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.ApiGalleryUploadWeb.Endpoint.HTTP']}]) at <0.756.0> exit with reason killed in context shutdown_error
2021-01-23 18:51:42.291 [error] <0.11661.1> CRASH REPORT Process <0.11661.1> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => perform,message => nil,module => 'Elixir.ExAws.Operation',reason => nil},[{'Elixir.ExAws.Operation',perform,[#{'__struct__' => 'Elixir.ExAws.Operation.S3',body => <<255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1,0,0,255,219,0,67,0,10,7,7,9,7,6,10,9,8,9,11,11,10,12,15,25,16,15,14,14,15,30,22,23,18,25,36,32,38,37,35,32,35,34,40,45,57,48,40,42,54,43,34,35,50,68,50,54,59,61,64,64,64,38,48,...>>,...},...],...},...]},...},...},...}
2021-01-23 18:51:42.291 [error] <0.11659.1> CRASH REPORT Process <0.11659.1> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => perform,message => nil,module => 'Elixir.ExAws.Operation',reason => nil},[{'Elixir.ExAws.Operation',perform,[#{'__struct__' => 'Elixir.ExAws.Operation.S3',body => <<255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1,0,0,255,219,0,67,0,10,7,7,9,7,6,10,9,8,9,11,11,10,12,15,25,16,15,14,14,15,30,22,23,18,25,36,32,38,37,35,32,35,34,40,45,57,48,40,42,54,43,34,35,50,68,50,54,59,61,64,64,64,38,48,...>>,...},...],...},...]},...},...},...}
2021-01-23 18:51:42.311 [error] <0.11661.1> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.11660.1> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => perform,message => nil,module => 'Elixir.ExAws.Operation',reason => nil},[{'Elixir.ExAws.Operation',perform,[#{'__struct__' => 'Elixir.ExAws.Operation.S3',body => <<255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1,0,0,255,219,0,67,0,10,7,7,9,7,6,10,9,8,9,11,11,10,12,15,25,16,15,14,14,15,30,22,23,18,25,36,32,38,37,35,32,35,34,40,45,57,48,40,42,54,43,34,35,50,68,50,54,59,61,64,64,64,38,48,...>>,...},...],...},...]},...},...}
2021-01-23 18:51:42.311 [error] <0.11659.1> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.11658.1> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => perform,message => nil,module => 'Elixir.ExAws.Operation',reason => nil},[{'Elixir.ExAws.Operation',perform,[#{'__struct__' => 'Elixir.ExAws.Operation.S3',body => <<255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1,0,0,255,219,0,67,0,10,7,7,9,7,6,10,9,8,9,11,11,10,12,15,25,16,15,14,14,15,30,22,23,18,25,36,32,38,37,35,32,35,34,40,45,57,48,40,42,54,43,34,35,50,68,50,54,59,61,64,64,64,38,48,...>>,...},...],...},...]},...},...}
2021-01-23 22:50:50.399 [error] <0.870.3> CRASH REPORT Process <0.870.3> with 0 neighbours exited with reason: {{{{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'image' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.404.0>,{call,{'queue.declare',0,<<"image">>,false,true,false,false,false,[]},none,<0.870.3>},70000]}},{'Elixir.ApiGalleryUploadWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',...},...},...]}},...},...}
2021-01-23 22:50:50.402 [error] <0.870.3> Cowboy stream 3 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.839.3> had its request process exit with reason: {{{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'image' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.404.0>,{call,{'queue.declare',0,<<"image">>,false,true,false,false,false,[]},none,<0.870.3>},70000]}},{'Elixir.ApiGalleryUploadWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',...},...},...]}},...}
2021-01-23 23:05:45.171 [error] <0.1014.3> CRASH REPORT Process <0.1014.3> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{<<"x-dead-letter-exchange">> => <<"ex.image.dlq">>,<<"x-message-ttl">> => 15000,<<"x-queue-type">> => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/queue.ex"},{line,44}]},{'Elixir.ApiGalleryUpload.ClientQueue',setup,...},...]},...},...},...}
2021-01-23 23:05:45.175 [error] <0.1014.3> Cowboy stream 3 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.1005.3> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{<<"x-dead-letter-exchange">> => <<"ex.image.dlq">>,<<"x-message-ttl">> => 15000,<<"x-queue-type">> => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/queue.ex"},{line,44}]},{'Elixir.ApiGalleryUpload.ClientQueue',setup,0,...},...]},...},...}
2021-01-23 23:07:34.570 [error] <0.1048.3> CRASH REPORT Process <0.1048.3> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{'x-dead-letter-exchange' => <<"ex.image.dlq">>,'x-message-ttl' => 15000,'x-queue-type' => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/queue.ex"},{line,44}]},{'Elixir.ApiGalleryUpload.ClientQueue',setup,0,[{file,"..."},...]},...]},...},...},...}
2021-01-23 23:07:34.573 [error] <0.1048.3> Cowboy stream 6 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.1005.3> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{'x-dead-letter-exchange' => <<"ex.image.dlq">>,'x-message-ttl' => 15000,'x-queue-type' => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/queue.ex"},{line,44}]},{'Elixir.ApiGalleryUpload.ClientQueue',setup,0,[{file,"li..."},...]},...]},...},...}
2021-01-23 23:09:28.574 [error] <0.1075.3> CRASH REPORT Process <0.1075.3> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{'x-dead-letter-exchange' => <<"ex.image.dlq">>,'x-message-ttl' => 15000,'x-queue-type' => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/q..."},...]},...]},...},...},...}
2021-01-23 23:09:28.581 [error] <0.1075.3> Cowboy stream 1 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.1074.3> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{'x-dead-letter-exchange' => <<"ex.image.dlq">>,'x-message-ttl' => 15000,'x-queue-type' => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/que..."},...]},...]},...},...}
2021-01-23 23:10:05.996 [error] <0.1100.3> CRASH REPORT Process <0.1100.3> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{'x-dead-letter-exchange' => <<"ex.image.dlq">>,'x-message-ttl' => 15000,'x-queue-type' => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/q..."},...]},...]},...},...},...}
2021-01-23 23:10:06.003 [error] <0.1100.3> Cowboy stream 2 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.1074.3> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => to_type_tuple,kind => nil,module => 'Elixir.AMQP.Utils'},[{'Elixir.AMQP.Utils',to_type_tuple,[#{'x-dead-letter-exchange' => <<"ex.image.dlq">>,'x-message-ttl' => 15000,'x-queue-type' => <<"classic">>}],[{file,"lib/amqp/utils.ex"},{line,5}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.AMQP.Queue',declare,3,[{file,"lib/amqp/que..."},...]},...]},...},...}
2021-01-23 23:10:14.679 [error] <0.1123.3> CRASH REPORT Process <0.1123.3> with 0 neighbours exited with reason: {{{{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'image.dlq' in vhost '/'">>}},{gen_server,call,[<0.895.3>,{call,{'queue.bind',0,<<"image.dlq">>,<<"ex.image.dlq">>,<<>>,false,[]},none,<0.1123.3>},70000]}},{'Elixir.ApiGalleryUploadWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 41847,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, def...">>,...},...}},...},...]}},...},...}
2021-01-23 23:10:14.680 [error] <0.1123.3> Cowboy stream 3 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.1074.3> had its request process exit with reason: {{{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'image.dlq' in vhost '/'">>}},{gen_server,call,[<0.895.3>,{call,{'queue.bind',0,<<"image.dlq">>,<<"ex.image.dlq">>,<<>>,false,[]},none,<0.1123.3>},70000]}},{'Elixir.ApiGalleryUploadWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 41847,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, defla...">>,...},...}},...},...]}},...}
2021-01-23 23:11:09.532 [error] <0.1150.3> CRASH REPORT Process <0.1150.3> with 0 neighbours exited with reason: {{{{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'image.dlq' in vhost '/'">>}},{gen_server,call,[<0.1146.3>,{call,{'queue.bind',0,<<"image.dlq">>,<<"ex.image.dlq">>,<<>>,false,[]},none,<0.1150.3>},70000]}},{'Elixir.ApiGalleryUploadWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 41847,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, de...">>,...},...}},...},...]}},...},...}
2021-01-23 23:11:09.536 [error] <0.1150.3> Cowboy stream 4 with ranch listener 'Elixir.ApiGalleryUploadWeb.Endpoint.HTTP' and connection process <0.1074.3> had its request process exit with reason: {{{{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'image.dlq' in vhost '/'">>}},{gen_server,call,[<0.1146.3>,{call,{'queue.bind',0,<<"image.dlq">>,<<"ex.image.dlq">>,<<>>,false,[]},none,<0.1150.3>},70000]}},{'Elixir.ApiGalleryUploadWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 41847,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, defl...">>,...},...}},...},...]}},...}
